// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJp4YF2vxSRl3fYxQHMrf22PJVux-OYRc',
    appId: '1:310732420549:web:9945b35331503920d747ac',
    messagingSenderId: '310732420549',
    projectId: 'khungolddb',
    authDomain: 'khungolddb.firebaseapp.com',
    storageBucket: 'khungolddb.firebasestorage.app',
    measurementId: 'G-6EZ2C257KF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIFJF9S_CPYMFKL_-RyACIHxhMDVbbA-s',
    appId: '1:310732420549:android:befccb5d007357afd747ac',
    messagingSenderId: '310732420549',
    projectId: 'khungolddb',
    storageBucket: 'khungolddb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLh4IyKr0yKKeKwPd2wKpfTAYwrhlfNWw',
    appId: '1:310732420549:ios:308c7b0f285b67b4d747ac',
    messagingSenderId: '310732420549',
    projectId: 'khungolddb',
    storageBucket: 'khungolddb.firebasestorage.app',
    iosBundleId: 'com.example.khungold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLh4IyKr0yKKeKwPd2wKpfTAYwrhlfNWw',
    appId: '1:310732420549:ios:308c7b0f285b67b4d747ac',
    messagingSenderId: '310732420549',
    projectId: 'khungolddb',
    storageBucket: 'khungolddb.firebasestorage.app',
    iosBundleId: 'com.example.khungold',
  );

}